### ISSUE TITLE
Testimonials Section

### ISSUE THREAD

**Issue by mike10911** [mike10911/michaelmundia#29]
### TODO:

- [ ] Design a new testimonials section
- [ ] Users should be able to add a new testimonial
- - [ ] Full Name  
- - [ ] Title in relation to Mike
- - [ ] Profile Pic
- - [ ] Linkedin Link
- - [ ] Email Address
- - [ ] Testimonial (400-word limit)
- [ ] Testimonial Should be saved to MongoDB
